// This file was autogenerated at deployment time picking the list of blacklisted modules defined in "blacklisted-modules.js" for network xdai
export const BLACKLISTED_MODULES: string[] = ["0x41ab49872ed459c840d0caecd47fcdc201c48307"]
