name: Deploy Mainnet

on:
  push:
    tags:
    - v*

env:
  GRAPHKEY: ${{secrets.GRAPHKEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Deploy
      run: npm run deploy:mainnet
