name: Deploy Testnets

on:
  push:
    branches:
    - '*'

env:
  GRAPHKEY: ${{secrets.GRAPHKEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Staging
      run: npm run deploy:staging
    - name: Rinkeby
      run: npm run deploy:rinkeby
    - name: Ropsten
      run: npm run deploy:ropsten
