name: Deploy Mainnet

on:
  push:
    tags:
    - v*

env:
  GRAPHKEY: ${{secrets.GITHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm run deploy:mainnet
